feat(client): add option to HttpConnector to enable or disable
hyperium/hyper pull request #2837
Opened 2022-05-20 11:27 UTC by mnpw

This adds `http_info` configuration option in `http::Config`. It can be used to enable or disable `HttpInfo`. 

`HttpInfo` is set through methods defined on `TcpStream` (`peer_addr()` and `local_addr()`). Configuration options have to be made available to `TcpStream` in order to enforce `http_info`. `HttpConnection` is added to achieve this.
 
Fixes #2833

Ps: Rust and oss newbie so apologies if I missed some obvious issue 😅

2022-05-22 09:58 UTC, ho-229 commented
I think you should open a new PR to submit breaking changes.

2022-05-24 22:10 UTC, seanmonstar requested changes
Thanks for the PR! I'm in favor of adding the configuration, though I believe we can do so without the breaking change I commented about below. :)

2022-05-24 22:10 UTC, seanmonstar commented on src/client/connect/http.rs
> +    type Response = HttpConnection;
This would be a breaking change. Can we provide the configuration without needing a new type?

2022-06-02 12:12 UTC, ho-229 commented
Are you still working on it🤔

2026-09-01 19:33 UTC, closed without merging