Expose ReadBufCursor::remaining and ReadBufCursor::put_slice
hyperium/hyper pull request #3700
Opened 2024-07-10 08:09 UTC by nox

There is currently no way to write to ReadBufCursor without unsafe code, even though writing a slice to it like one would do to a Buf shouldn't require unsafe code.

2024-07-10 08:16 UTC, nox commented
There is also #3515 that is similar, but more involved.

2024-07-12 17:27 UTC, seanmonstar requested changes
Seems fair to add these :)

2024-07-12 17:27 UTC, seanmonstar commented on src/rt/io.rs
> +    /// This value is equal tho the length of the slice returned by `as_mut()``.
```suggestion
    /// This value is equal to the length of the slice returned by `as_mut()``.
```

2024-07-12 17:27 UTC, seanmonstar commented on src/rt/io.rs
> +    /// `self` must have enough remaining capacity to contain all of `src`.
How about adding a `# Panics` heading in between these two lines?

2024-07-15 08:01 UTC, nox commented
@seanmonstar I addressed both comments.

2024-07-15 18:25 UTC, merged

2024-10-14 10:28 UTC, nox commented
Can we release 1.5 to get this please?